# Generated by Django 4.1.2 on 2022-11-09 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Darbo_zona_sandelyje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_code', models.CharField(max_length=2, verbose_name='Zonos kodas')),
                ('zone_description', models.CharField(max_length=80, verbose_name='Zonos aprasymas pvz 60-Tiko')),
            ],
        ),
        migrations.CreateModel(
            name='Darbuotojas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picker_code', models.CharField(max_length=3, verbose_name='rinkejo_kodas')),
                ('first_name', models.CharField(max_length=80, verbose_name='Vardas')),
                ('last_name', models.CharField(max_length=80, verbose_name='Pavardė')),
                ('position', models.CharField(blank=True, choices=[('grupes vadovas', 'grupes vadovas'), ('grupes vadovo asistentas', 'grupes vadovo asistentas'), ('grupes vadovo asistentas', 'grupes vadovo asistentas'), ('prekiu komplektuotojas', 'prekiu komplektuotojas')], default='prekiu komplektuotojas', help_text='Darbuotojo pareigos', max_length=80)),
                ('photo', models.ImageField(null=True, upload_to='photos', verbose_name='Darbuotojo foto arba avataras')),
                ('working_since', models.DateField(blank=True, null=True, verbose_name='Darbo pradžia LIDL imoneje')),
                ('working_zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lm.darbo_zona_sandelyje')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True, verbose_name='kada zinute sukurta')),
                ('note_type', models.CharField(blank=True, choices=[('zemas', 'paprasta zinute sau'), ('aukstas', 'reikia informuoti tiesiogini vadova'), ('m_ideja', 'metu ideja')], default='da', max_length=40, verbose_name='Zinutes tipas')),
                ('summary', models.TextField(help_text='Svarbu aprasyti placiau, aciu uz jusu laika.', max_length=1000, verbose_name='Pastebejimo/zinutes aprasymas')),
                ('darbuotojas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lm.darbuotojas')),
            ],
        ),
        migrations.CreateModel(
            name='Krautuvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('krautuvo_id', models.IntegerField(verbose_name='krautuvo numeris')),
                ('data_taken', models.DateField(blank=True, null=True, verbose_name='kada krautuvas paiimtas')),
                ('data_returned', models.DateField(blank=True, null=True, verbose_name='kada krautuvas grazintas')),
                ('notes', models.TextField(help_text='labai svarbu pamineti ir smulkiausius gedimus, dekojame.', max_length=1000, verbose_name='Pastebejimai naudojantis krautuvu')),
                ('note_type', models.CharField(blank=True, choices=[('aukstas', 'aukstas'), ('vidutinis', 'vidutinis'), ('zemas', 'zemas')], default='da', max_length=40, verbose_name='Rasto gedimo/pastabos svarba')),
                ('darbuotojas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lm.darbuotojas')),
            ],
        ),
        migrations.CreateModel(
            name='Darbo_laiko_irasai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True, verbose_name='kada dirbta')),
                ('status', models.CharField(blank=True, choices=[('darbas', 'darbas'), ('pertrauka', 'pertrauka'), ('pietu pertrauka', 'pietu pertrauka')], default='da', max_length=40, verbose_name='Darbo grafiko laiko tipas')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='darbo iraso trukme')),
                ('picked_boxes', models.IntegerField(verbose_name='Surinkta deziu per irasa')),
                ('darbuotojas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lm.darbuotojas')),
                ('working_zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lm.darbo_zona_sandelyje')),
            ],
            options={
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Darbo_grafikas_planas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True, verbose_name='kada dirbs')),
                ('day_status', models.CharField(blank=True, choices=[('darbas', 'darbas'), ('laisvadienis', 'laisvadienis'), ('atostogos', 'atostogos'), ('mamadienis', 'mamadienis'), ('nedarbiningumas', 'nedarbiningumas'), ('nedarbo diena', 'nedarbo diena'), ('karine tarnyba', 'karine tarnyba'), ('idirbis kitame skyriuje', 'idirbis kitame skyriuje')], default='darbas', max_length=40, verbose_name='Dienos statusas')),
                ('position', models.CharField(blank=True, choices=[('grupes vadovas', 'grupes vadovas'), ('grupes vadovo asistentas', 'grupes vadovo asistentas'), ('grupes vadovo asistentas', 'grupes vadovo asistentas'), ('prekiu komplektuotojas', 'prekiu komplektuotojas')], default='prekiu komplektuotojas', help_text='Darbuotojo pareigos', max_length=80)),
                ('shift_status', models.CharField(blank=True, choices=[('8', '100% etatas -8val'), ('6', '75% etatas -6val'), ('4', '50% etatas -4val')], default='da', max_length=40, verbose_name='Darbo status')),
                ('darbuotojas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lm.darbuotojas')),
                ('working_zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lm.darbo_zona_sandelyje')),
            ],
            options={
                'ordering': ['data', 'darbuotojas'],
            },
        ),
    ]
