# Generated by Django 4.1.3 on 2022-11-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='krautuvas',
            options={'ordering': ['data_taken', 'note_type']},
        ),
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['note_type', 'data']},
        ),
        migrations.RemoveField(
            model_name='krautuvas',
            name='data_returned',
        ),
        migrations.AlterField(
            model_name='darbo_grafikas_planas',
            name='shift_status',
            field=models.CharField(blank=True, choices=[('8', '100% etatas -8val'), ('6', '75% etatas -6val'), ('4', '50% etatas -4val')], default='8', max_length=40, verbose_name='Darbo status'),
        ),
        migrations.AlterField(
            model_name='darbo_zona_sandelyje',
            name='zone_code',
            field=models.CharField(blank=True, choices=[('20', '20 - HR'), ('40', '40 - MOPRO'), ('41', '41 - Pienas'), ('60', '60 - TIKO'), ('61', '61 - BakeOff'), ('70', '70 - Fruits'), ('80', '80 - Mėsa'), ('90', '90 - NonFood')], default='40', help_text='Darbo zona sandėlyje', max_length=80),
        ),
        migrations.AlterField(
            model_name='krautuvas',
            name='note_type',
            field=models.CharField(blank=True, choices=[('aukstas', 'aukstas'), ('vidutinis', 'vidutinis'), ('zemas', 'zemas'), ('be pastebejimu', 'be pastebejimu')], default='be pastebejimu', max_length=40, verbose_name='Rasto gedimo/pastabos svarba'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='note_type',
            field=models.CharField(blank=True, choices=[('9', 'paprasta zinute sau'), ('0', 'reikia informuoti tiesiogini vadova'), ('8', 'metu ideja')], default='9', max_length=40, verbose_name='Zinutes tipas'),
        ),
    ]
