# Generated by Django 4.1.3 on 2022-11-24 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lm', '0002_alter_krautuvas_options_alter_notes_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='krautuvas',
            options={'ordering': ['data_taken', 'note_type'], 'verbose_name_plural': 'krautuvai'},
        ),
    ]
