# Generated by Django 4.1.3 on 2022-12-05 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lm', '0002_profilis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilis',
            old_name='nuotrauka',
            new_name='photo',
        ),
    ]
