# Generated by Django 4.1.3 on 2022-12-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lm', '0003_rename_nuotrauka_profilis_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', help_text='Darbuotojo foto arba avataras', null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='profilis',
            name='photo',
            field=models.ImageField(default='default.png', null=True, upload_to='profile_pics'),
        ),
    ]
