# Generated by Django 4.1.3 on 2022-11-24 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lm', '0003_alter_krautuvas_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darbo_grafikas_planas',
            name='darbuotojas',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lm.darbuotojas'),
        ),
        migrations.AlterField(
            model_name='darbo_grafikas_planas',
            name='data',
            field=models.DateField(blank=True, help_text='kada dirbs', null=True),
        ),
        migrations.AlterField(
            model_name='darbo_grafikas_planas',
            name='day_status',
            field=models.CharField(blank=True, choices=[('darbas', 'darbas'), ('laisvadienis', 'laisvadienis'), ('atostogos', 'atostogos'), ('mamadienis', 'mamadienis'), ('nedarbiningumas', 'nedarbiningumas'), ('nedarbo diena', 'nedarbo diena'), ('karine tarnyba', 'karine tarnyba'), ('idirbis kitame skyriuje', 'idirbis kitame skyriuje')], default='darbas', help_text='Dienos statusas', max_length=40),
        ),
        migrations.AlterField(
            model_name='darbo_grafikas_planas',
            name='shift_status',
            field=models.CharField(blank=True, choices=[('8', '100% etatas -8val'), ('6', '75% etatas -6val'), ('4', '50% etatas -4val')], default='8', help_text='Darbo status', max_length=40),
        ),
        migrations.AlterField(
            model_name='darbo_grafikas_planas',
            name='working_zone',
            field=models.ForeignKey(max_length=80, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lm.darbo_zona_sandelyje'),
        ),
        migrations.AlterField(
            model_name='darbo_laiko_irasai',
            name='darbuotojas',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lm.darbuotojas'),
        ),
        migrations.AlterField(
            model_name='darbo_laiko_irasai',
            name='data',
            field=models.DateField(blank=True, help_text='kada dirbta', null=True),
        ),
        migrations.AlterField(
            model_name='darbo_laiko_irasai',
            name='duration',
            field=models.DurationField(blank=True, help_text='darbo iraso trukme', null=True),
        ),
        migrations.AlterField(
            model_name='darbo_laiko_irasai',
            name='picked_boxes',
            field=models.IntegerField(help_text='Surinkta deziu per irasa'),
        ),
        migrations.AlterField(
            model_name='darbo_laiko_irasai',
            name='status',
            field=models.CharField(blank=True, choices=[('darbas', 'darbas'), ('pertrauka', 'pertrauka'), ('pietu pertrauka', 'pietu pertrauka')], default='darbas', help_text='Darbo grafiko laiko tipas', max_length=40),
        ),
        migrations.AlterField(
            model_name='darbo_laiko_irasai',
            name='working_zone',
            field=models.ForeignKey(max_length=80, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lm.darbo_zona_sandelyje'),
        ),
        migrations.AlterField(
            model_name='darbo_zona_sandelyje',
            name='zone_description',
            field=models.CharField(help_text='Zonos aprasymas pvz 60-Tiko', max_length=80),
        ),
        migrations.AlterField(
            model_name='darbuotojas',
            name='first_name',
            field=models.CharField(help_text='Vardas', max_length=80),
        ),
        migrations.AlterField(
            model_name='darbuotojas',
            name='last_name',
            field=models.CharField(help_text='Pavardė', max_length=80),
        ),
        migrations.AlterField(
            model_name='darbuotojas',
            name='photo',
            field=models.ImageField(help_text='Darbuotojo foto arba avataras', null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='darbuotojas',
            name='picker_code',
            field=models.CharField(help_text='rinkejo_kodas', max_length=3),
        ),
        migrations.AlterField(
            model_name='darbuotojas',
            name='working_since',
            field=models.DateField(blank=True, help_text='Darbo pradžia LIDL imoneje', null=True),
        ),
        migrations.AlterField(
            model_name='krautuvas',
            name='data_taken',
            field=models.DateField(blank=True, help_text='kada krautuvas paiimtas', null=True),
        ),
        migrations.AlterField(
            model_name='krautuvas',
            name='krautuvo_id',
            field=models.IntegerField(help_text='krautuvo numeris'),
        ),
        migrations.AlterField(
            model_name='krautuvas',
            name='note_type',
            field=models.CharField(blank=True, choices=[('aukstas', 'aukstas'), ('vidutinis', 'vidutinis'), ('zemas', 'zemas'), ('be pastebejimu', 'be pastebejimu')], default='be pastebejimu', help_text='Rasto gedimo/pastabos svarba', max_length=40),
        ),
        migrations.AlterField(
            model_name='krautuvas',
            name='notes',
            field=models.TextField(help_text='labai svarbu pamineti ir smulkiausius gedimus, dekojame.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='notes',
            name='data',
            field=models.DateField(blank=True, help_text='kada zinute sukurta', null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='note_type',
            field=models.CharField(blank=True, choices=[('9', 'paprasta zinute sau'), ('0', 'reikia informuoti tiesiogini vadova'), ('8', 'metu ideja')], default='9', help_text='Zinutes tipas', max_length=40),
        ),
        migrations.AlterField(
            model_name='notes',
            name='summary',
            field=models.TextField(help_text='Svarbu aprasyti placiau, aciu uz jusu laika.', max_length=1000),
        ),
    ]
