# Generated by Django 4.1.3 on 2022-12-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lm', '0004_alter_myuser_photo_alter_profilis_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', help_text='Darbuotojo foto arba avataras', null=True, upload_to='profile_pics'),
        ),
    ]
