# Generated by Django 4.1.3 on 2022-11-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lm', '0004_alter_darbo_grafikas_planas_darbuotojas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='darbo_laiko_irasai',
            options={'ordering': ['data'], 'verbose_name': '{% trans "Working record" %}', 'verbose_name_plural': '{% trans "Working records" %}'},
        ),
        migrations.AlterModelOptions(
            name='darbo_zona_sandelyje',
            options={'ordering': ['zone_code'], 'verbose_name': '{% trans "Working zone" %}', 'verbose_name_plural': '{% trans "Working zone" %}'},
        ),
        migrations.AlterModelOptions(
            name='darbuotojas',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': '{% trans "Worker" %}', 'verbose_name_plural': '{% trans "Workers" %}'},
        ),
        migrations.AlterModelOptions(
            name='krautuvas',
            options={'ordering': ['data_taken', 'note_type'], 'verbose_name': '{% trans "Vehicle" %}', 'verbose_name_plural': '{% trans "Vehicles" %}'},
        ),
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['note_type', 'data'], 'verbose_name': '{% trans "Note" %}', 'verbose_name_plural': '{% trans "Notes" %}'},
        ),
        migrations.AddField(
            model_name='darbuotojas',
            name='working_department',
            field=models.CharField(blank=True, choices=[('Vilniaus apsk', 'Vilniaus apsk'), ('Vilniaus regioninis sandėlys', 'Vilniaus regioninis sandėlys'), ('Kauno apsk', 'Kauno apsk'), ('Kauno regioninis sandėlys', 'Kauno regioninis sandėlys'), ('Klaipėdos apsk', 'Klaipėdos apsk')], default='Kauno regioninis sandėlys', help_text='Kurioje (-iame) apskrityje/logistikos sandėlyje dirbate', max_length=80),
        ),
        migrations.DeleteModel(
            name='Darbo_grafikas_planas',
        ),
    ]
