# Generated by Django 4.1.3 on 2022-11-26 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lm', '0005_alter_darbo_laiko_irasai_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='darbo_zona_sandelyje',
            options={'ordering': ['zone_code'], 'verbose_name': '{% trans "Working zone" %}', 'verbose_name_plural': '{% trans "Working zones" %}'},
        ),
        migrations.AlterField(
            model_name='darbo_laiko_irasai',
            name='data',
            field=models.DateField(blank=True, help_text='kada dirbta', null=True, verbose_name='Date of working record'),
        ),
        migrations.AlterField(
            model_name='darbo_laiko_irasai',
            name='duration',
            field=models.DurationField(blank=True, help_text='darbo iraso trukme', null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='darbo_laiko_irasai',
            name='picked_boxes',
            field=models.IntegerField(help_text='Surinkta deziu per irasa', verbose_name='Picked boxes per duration'),
        ),
        migrations.AlterField(
            model_name='darbo_laiko_irasai',
            name='status',
            field=models.CharField(blank=True, choices=[('darbas', 'darbas'), ('pertrauka', 'pertrauka'), ('pietu pertrauka', 'pietu pertrauka')], default='darbas', help_text='Darbo grafiko laiko tipas', max_length=40, verbose_name='Type of working record'),
        ),
        migrations.AlterField(
            model_name='darbo_zona_sandelyje',
            name='zone_code',
            field=models.CharField(blank=True, choices=[('20', '20 - HR'), ('40', '40 - MOPRO'), ('41', '41 - Pienas'), ('60', '60 - TIKO'), ('61', '61 - BakeOff'), ('70', '70 - Fruits'), ('80', '80 - Mėsa'), ('90', '90 - NonFood')], default='40', help_text='Darbo zona sandėlyje', max_length=80, verbose_name='Working zone code'),
        ),
        migrations.AlterField(
            model_name='darbo_zona_sandelyje',
            name='zone_description',
            field=models.CharField(help_text='Zonos aprasymas pvz 60-Tiko', max_length=80, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='darbuotojas',
            name='first_name',
            field=models.CharField(help_text='Vardas', max_length=80, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='darbuotojas',
            name='last_name',
            field=models.CharField(help_text='Pavardė', max_length=80, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='darbuotojas',
            name='picker_code',
            field=models.CharField(help_text='rinkejo_kodas', max_length=3, verbose_name='Piker code'),
        ),
        migrations.AlterField(
            model_name='darbuotojas',
            name='position',
            field=models.CharField(blank=True, choices=[('grupes vadovas', 'grupes vadovas'), ('grupes vadovo asistentas', 'grupes vadovo asistentas'), ('grupes vadovo asistentas', 'grupes vadovo asistentas'), ('prekiu komplektuotojas', 'prekiu komplektuotojas')], default='prekiu komplektuotojas', help_text='Darbuotojo pareigos', max_length=80, verbose_name='Working position'),
        ),
        migrations.AlterField(
            model_name='darbuotojas',
            name='working_department',
            field=models.CharField(blank=True, choices=[('Vilniaus apsk', 'Vilniaus apsk'), ('Vilniaus regioninis sandėlys', 'Vilniaus regioninis sandėlys'), ('Kauno apsk', 'Kauno apsk'), ('Kauno regioninis sandėlys', 'Kauno regioninis sandėlys'), ('Klaipėdos apsk', 'Klaipėdos apsk')], default='Kauno regioninis sandėlys', help_text='Kurioje (-iame) apskrityje/logistikos sandėlyje dirbate', max_length=80, verbose_name='Working disctric or logistic warehouse'),
        ),
        migrations.AlterField(
            model_name='darbuotojas',
            name='working_since',
            field=models.DateField(blank=True, help_text='Darbo pradžia LIDL imoneje', null=True, verbose_name='Working since'),
        ),
        migrations.AlterField(
            model_name='krautuvas',
            name='data_taken',
            field=models.DateField(blank=True, help_text='kada krautuvas paiimtas', null=True, verbose_name='Date when vechiles was taken'),
        ),
        migrations.AlterField(
            model_name='krautuvas',
            name='krautuvo_id',
            field=models.IntegerField(help_text='krautuvo numeris', verbose_name='Vechiles ID "3 digits"'),
        ),
        migrations.AlterField(
            model_name='krautuvas',
            name='note_type',
            field=models.CharField(blank=True, choices=[('aukstas', 'aukstas'), ('vidutinis', 'vidutinis'), ('zemas', 'zemas'), ('be pastebejimu', 'be pastebejimu')], default='be pastebejimu', help_text='Rasto gedimo/pastabos svarba', max_length=40, verbose_name='Importance of the notes'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='data',
            field=models.DateField(blank=True, help_text='kada zinute sukurta', null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='note_type',
            field=models.CharField(blank=True, choices=[('9', 'paprasta zinute sau'), ('0', 'reikia informuoti tiesiogini vadova'), ('8', 'metu ideja')], default='9', help_text='Zinutes tipas', max_length=40, verbose_name='Type of notes'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='summary',
            field=models.TextField(help_text='Svarbu aprasyti placiau, aciu uz jusu laika.', max_length=1000, verbose_name='Description of the notes'),
        ),
    ]
