# Generated by Django 4.1.3 on 2022-11-26 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lm', '0006_alter_darbo_zona_sandelyje_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='darbo_laiko_irasai',
            options={'ordering': ['data'], 'verbose_name': 'Working record', 'verbose_name_plural': 'Working records'},
        ),
        migrations.AlterModelOptions(
            name='darbo_zona_sandelyje',
            options={'ordering': ['zone_code'], 'verbose_name': 'Working zone', 'verbose_name_plural': 'Working zones'},
        ),
        migrations.AlterModelOptions(
            name='darbuotojas',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Worker', 'verbose_name_plural': 'Workers'},
        ),
        migrations.AlterModelOptions(
            name='krautuvas',
            options={'ordering': ['data_taken', 'note_type'], 'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['data', 'note_type'], 'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
    ]
