# Generated by Django 4.1.3 on 2022-11-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lm', '0007_alter_darbo_laiko_irasai_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='krautuvas',
            name='status',
            field=models.CharField(blank=True, choices=[('ready', 'ready'), ('taken', 'taken'), ('waiting_for_repair', 'waiting_for_repair'), ('repairing', 'repairing')], default='taken', help_text='Status', max_length=30),
        ),
    ]
