# Generated by Django 4.1.3 on 2022-12-06 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lm', '0007_alter_krautuvas_krautuvo_id_alter_krautuvas_notes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TakeMachine',
        ),
    ]
