# Generated by Django 4.1.3 on 2022-12-03 03:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lm', '0008_krautuvas_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='krautuvas',
            options={'ordering': ['krautuvo_id'], 'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.AlterField(
            model_name='darbo_laiko_irasai',
            name='duration',
            field=models.CharField(blank=True, default=datetime.timedelta(seconds=25200), help_text='darbo iraso trukme', max_length=20, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='darbo_laiko_irasai',
            name='picked_boxes',
            field=models.IntegerField(blank=True, default='0', help_text='Surinkta deziu per irasa', null=True, verbose_name='Picked boxes per duration'),
        ),
        migrations.AlterField(
            model_name='darbo_zona_sandelyje',
            name='zone_code',
            field=models.CharField(blank=True, choices=[('20', '20 - HR'), ('40', '40 - MOPRO'), ('41', '41 - Pienas'), ('60', '60 - TIKO'), ('61', '61 - BakeOff'), ('70', '70 - Fruits'), ('50', '50 - Mėsa'), ('90', '90 - NonFood')], default='40', help_text='Darbo zona sandėlyje', max_length=80, unique=True, verbose_name='Working zone code'),
        ),
        migrations.AlterField(
            model_name='darbuotojas',
            name='photo',
            field=models.ImageField(blank=True, help_text='Darbuotojo foto arba avataras', null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='darbuotojas',
            name='picker_code',
            field=models.CharField(help_text='rinkejo_kodas', max_length=3, unique=True, verbose_name='Piker code'),
        ),
        migrations.AlterField(
            model_name='krautuvas',
            name='darbuotojas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lm.darbuotojas'),
        ),
        migrations.AlterField(
            model_name='krautuvas',
            name='krautuvo_id',
            field=models.IntegerField(help_text='krautuvo numeris', unique=True, verbose_name='Vechiles ID "3 digits"'),
        ),
        migrations.AlterField(
            model_name='krautuvas',
            name='note_type',
            field=models.CharField(blank=True, choices=[('aukstas', 'aukstas'), ('vidutinis', 'vidutinis'), ('zemas', 'zemas'), ('be pastebejimu', 'be pastebejimu')], default='be pastebejimu', help_text='Rasto gedimo/pastabos svarba', max_length=40, null=True, verbose_name='Importance of the notes'),
        ),
        migrations.AlterField(
            model_name='krautuvas',
            name='notes',
            field=models.TextField(blank=True, help_text='labai svarbu pamineti ir smulkiausius gedimus, dekojame.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='krautuvas',
            name='status',
            field=models.CharField(blank=True, choices=[('ready', 'ready'), ('taken', 'taken'), ('waiting_for_repair', 'waiting_for_repair'), ('repairing', 'repairing')], default='taken', help_text='Status', max_length=30, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='note_type',
            field=models.CharField(blank=True, choices=[('9', 'paprasta zinute sau'), ('0', 'reikia informuoti tiesiogini vadova'), ('8', 'metu ideja')], default='9', help_text='Zinutes tipas', max_length=40, null=True, verbose_name='Type of notes'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='summary',
            field=models.TextField(blank=True, help_text='Svarbu aprasyti placiau, aciu uz jusu laika.', max_length=1000, null=True, verbose_name='Description of the notes'),
        ),
    ]
